# Generated by Django 4.2.2 on 2023-06-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendingstonesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sendingstonesapi.game'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='sendingstonesapi.gamer'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_master', to='sendingstonesapi.gamer'),
        ),
    ]
